#!/bin/bash 
# This is responsible for checking to make sure that the master instance is up and running
# and if it is not, take over the master role and reconfigure the cloud
case $1 in 
start) 
    instance start_maintain
    ;; 
stop) 
    instance stop_maintain
    ;; 
status)
    ps aux | awk '{print $2}' | grep `cat /var/run/pool_maintain.pid`
    ;; 
*) 
    echo "Syntax incorrect. You need one of {start|stop|status}" 
    ;; 
esac