require "rubygems"
require "json"
require "#{::File.dirname(__FILE__)}/../../vendor/gems/dslify/lib/dslify"
require "poolparty/poolparty/default"
require "poolparty/schema"
require "poolparty/net/init"